version: 0.2
phases:
  install:
    commands:
      - apt-get install -y php8.1-cli php8.1-mbstring php8.1-zip unzip
      - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
  build:
    commands:
      - composer install --no-interaction --no-progress
artifacts:
  files:
    - '**/*'
  discard-paths: no
